name: synaptech_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - mne>=1.0
  - numpy
  - python=3.10
  - pytorch
  - scipy
  - torchaudio
  - torchvision
  - ipykernel
  - pandas
  - python-dotenv 
  - wandb